### ISSUE TITLE
Configure go-c.at Domain to point to this Repo

### ISSUE THREAD

**Issue by ThomasChr** [go-cat/go-cat#3]

**Comment by burned42** [comment]
Can be configured at https://github.com/go-cat/go-cat/settings
Also see https://help.github.com/articles/using-a-custom-domain-with-github-pages/

@EduardBaer ? :)

**Comment by ThomasChr** [comment]
I have no access to the Github Settings of this repo, nor to the DNS of the Domain.

**Comment by EduardBaer** [comment]
I can't access the settings page either.

**Comment by burned42** [comment]
I just set the configuration of the repository, so maybe it's just the DNS that's left to do?

https://help.github.com/articles/setting-up-an-apex-domain/

**Comment by EduardBaer** [comment]
I updated the DNS records. I guess we will see tomorrow if it works :smile:

**Comment by ThomasChr** [comment]
Seems to work, only Certificate is not working at the moment.

**Comment by burned42** [comment]
It says: ```[ ] Enforce HTTPS — Not yet available for your site because the certificate has not finished being issued.```

I guess we just have to wait a bit.

**Comment by ThomasChr** [comment]
Now working!

**Comment by burned42** [comment]
Yes, now I was able to activate `Enforce HTTPS` :)
